=====================================================================================================
Files already downloaded and verified
name: cifar_icassp/distillation
model: epoch_03.pt
defense: distillation
seed: 0
gpu_number: 0
load: False
batch_size: 32
lr: 0.001
epoch: 3
epsilon: 8.3
eta: 1e-05
dist_temp: 20
teacher: teacher.pt
attack: fgsm
budget: 0.05
perturbation: linf
alpha: 0.01
max_iter: 40
random_start: True
Start training
Epoch 1: 0/50000 (0%)
Epoch 1: 19200/50000 (38%)
Epoch 1: 38400/50000 (77%)
Epoch: 1, Loss: 2.289999, Accuracy: 10.25%
Epoch 2: 0/50000 (0%)
Epoch 2: 19200/50000 (38%)
Epoch 2: 38400/50000 (77%)
Epoch: 2, Loss: 1.080164, Accuracy: 88.14%
Epoch 3: 0/50000 (0%)
Epoch 3: 19200/50000 (38%)
Epoch 3: 38400/50000 (77%)
Epoch: 3, Loss: 0.387951, Accuracy: 84.96%
Training time (s): 9060.193512678146
=====================================================================================================
Files already downloaded and verified
name: cifar_icassp/adv_train
model: epoch_03.pt
defense: adv_train
seed: 0
gpu_number: 0
load: False
batch_size: 32
lr: 0.001
epoch: 3
epsilon: 8.3
eta: 1e-05
dist_temp: 20
teacher: teacher.pt
attack: fgsm
budget: 0.0627
perturbation: linf
alpha: 0.01
max_iter: 40
random_start: True
Start training
Epoch 1: 0/50000 (0%)
Epoch 1: 19200/50000 (38%)
Epoch 1: 38400/50000 (77%)
Epoch: 1, Loss: 1.575560, Accuracy: 45.87%
Traceback (most recent call last):
  File "/home/loic/geo_cifar/train_cifar.py", line 259, in <module>
    main()
  File "/home/loic/geo_cifar/train_cifar.py", line 255, in main
    one_run(param)
  File "/home/loic/geo_cifar/train_cifar.py", line 233, in one_run
    training(param, device, trainset, testset, model, reg_model, attack)
  File "/home/loic/geo_cifar/train_cifar.py", line 215, in training
    torch.save(checkpoint, f'models/{param["name"]}/epoch_{epoch:02d}.pt')
  File "/home/loic/anaconda3/envs/robust/lib/python3.9/site-packages/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/home/loic/anaconda3/envs/robust/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/loic/anaconda3/envs/robust/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/cifar_icassp/adv_train/epoch_01.pt'
